/**
 * ---------------------------------------------------------------------------------
 * DO NOT EDIT THIS FILE. It is machine-generated by 'sanity typegen generate'.
 * ---------------------------------------------------------------------------------
 */

import type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityFile,
  SanityGeoPoint,
  SanityBlock,
  SanityDocument,
  SanityImageCrop,
  SanityImageHotspot,
  SanityKeyed,
  SanityImageAsset,
  SanityImageMetadata,
  SanityImageDimensions,
  SanityImagePalette,
  SanityImagePaletteSwatch,
} from "sanity-codegen";

export type {
  SanityReference,
  SanityKeyedReference,
  SanityAsset,
  SanityImage,
  SanityFile,
  SanityGeoPoint,
  SanityBlock,
  SanityDocument,
  SanityImageCrop,
  SanityImageHotspot,
  SanityKeyed,
  SanityImageAsset,
  SanityImageMetadata,
  SanityImageDimensions,
  SanityImagePalette,
  SanityImagePaletteSwatch,
};

/**
 * Testimonial
 *
 *
 */
export interface Testimonial extends SanityDocument {
  _type: "testimonial";

  /**
   * Name — `string`
   *
   *
   */
  name?: string;

  /**
   * Role — `string`
   *
   *
   */
  role?: string;

  /**
   * Content — `text`
   *
   *
   */
  content?: string;

  /**
   * Avatar — `image`
   *
   *
   */
  avatar?: {
    _type: "image";
    asset: SanityReference<SanityImageAsset>;
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
}

/**
 * FAQ Item
 *
 *
 */
export interface FaqItem extends SanityDocument {
  _type: "faqItem";

  /**
   * Question — `string`
   *
   *
   */
  question?: string;

  /**
   * Answer — `text`
   *
   *
   */
  answer?: string;
}

export type Documents = Testimonial | FaqItem;